env_id: "Humanoid-v5"
policy: "MlpLstmPolicy"
n_envs: 4
total_timesteps: 30000000
learning_rate: 0.0001
batch_size: 8192
n_steps: 2048
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
ent_coef: 0.001
clip_range: 0.2
policy_net: [256, 256]
value_net: [256, 256]
clip_obs: 10.0
device: cuda

early_stopper:
  enabled: true
  patience: 15
  min_delta: 1.0
  reward_key: avg_reward
  reward_threshold: null
  fail_on_nan: true
  max_runtime_minutes: 240
