env_id: Humanoid-v5
sampling_strategy: balanced
sampling_goals:
  - name: walk_backward
    weight: 100.0
  - name: walk_forward
    weight: 100.0
  - name: turn_left
    weight: 100.0
  - name: turn_right
    weight: 100.0
  - name: stand_still
    weight: 100.0
