apiVersion: batch/v1
kind: Job
metadata:
  name: {{ job_name }}
spec:
  template:
    spec:
      containers:
      - name: {{ container_name }}
        image: {{ docker_image }}
        command: {{ command }}
        args: {{ args }}
        volumeMounts:
        - name: workspace
          mountPath: /workspace
        env:
        - name: WORKSPACE_DIR
          value: /workspace
        resources:
          limits:
            nvidia.com/gpu: {{ gpu }}
            cpu: {{ cpu }}
            memory: {{ memory }}
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: flex-rl-pvc
  backoffLimit: 1
