FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    build-essential \
    libssl-dev \
    libffi-dev \
    && apt-get clean

# Create work directory
WORKDIR /workspace

# Copy and install Python dependencies
COPY docker/requirements-cpu.txt /tmp/requirements.txt
RUN pip install --upgrade pip && pip install --no-cache-dir -r /tmp/requirements.txt

CMD [ "bash" ]
