# yaml-language-server: $schema=../config.schema.json
env_id: "Humanoid-v5"

policy: "MlpLstmPolicy"
n_envs: 2
total_timesteps: 10000000
learning_rate: 0.0003
batch_size: 4096
n_steps: 2048
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
ent_coef: 0.001
clip_range: 0.2
policy_net: [256, 256]
value_net: [256, 256]
clip_obs: 10.0

snapshot_freq: 100000
eval_freq: 100000
eval_episodes: 20

sampling_strategy: "balanced"
sampling_goals:
  - name: "walk_backward"
    weight: 500.0
  - name: "walk_forward"
    weight: 500.0
  - name: "turn_left"
    weight: 500.0
  - name: "turn_right"
    weight: 500.0
  - name: "stand_still"
    weight: 500.0
