model_id: meta-llama/Meta-Llama-3-8B-Instruct
attn_implementation: sdpa
torch_dtype: float16
prompt: >
  Respond with one action.
  Available actions: [move_up, move_right, move_left, move_down].
  Coords are in (x, y), where up = +y down = -y left = -x right = +x.
  Agent coords: 15, 15.
  Target coords: 30, 25.
  Which action brings the agent closest to the target?
