
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rl-training.fullname" . }}
  labels:
    {{- include "rl-training.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rl-training.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rl-training.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{- toYaml .Values.training.command | nindent 12 }}
          args: {{- toYaml .Values.training.args | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      restartPolicy: Always
      
