{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rl-training.serviceAccountName" . }}
  labels:
    {{- include "rl-training.labels" . | nindent 4 }}
{{- end }}
